databases:
  - name: final-marketplace-api
    databaseName: final-marketplace-api
    user: final-marketplace-api

services:
  - type: web
    name: final-marketplace-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: final-marketplace-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false